export const pics=[
    "../assets/images/img-1.jpg",
    "../assets/images/img-2.jpg",
    "../assets/images/img-3.jpg",
    "../assets/images/img-4.jpg",
    "../assets/images/img-5.jpg",
    "../assets/images/img-6.jpg",
    "../assets/images/img-7.jpg",
    "../assets/images/img-8.jpg",
    "../assets/images/img-9.jpg",
    "../assets/images/img-10.jpg",
    "../assets/images/img-11.jpg",
    "../assets/images/img-12.jpg",
    "../assets/images/img-13.jpg",
    "../assets/images/img-14.jpg",
    "../assets/images/img-15.jpg",
];